//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain single attribute of type &apos;{0}&apos; declared on &apos;{1}&apos; because multiple attributes are of type &apos;{0}&apos;..
        /// </summary>
        internal static string AttributeProvider_AmbiguousAttributeMatch {
            get {
                return ResourceManager.GetString("AttributeProvider_AmbiguousAttributeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified object of type &apos;{0}&apos; cannot be compared to instance of type &apos;{1}&apos;..
        /// </summary>
        internal static string Comparable_IncomparableType {
            get {
                return ResourceManager.GetString("Comparable_IncomparableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start this scope because a more restrive scope is still active..
        /// </summary>
        internal static string Context_IllegalScopeStarted {
            get {
                return ResourceManager.GetString("Context_IllegalScopeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time span specified: [{0}, {1}]..
        /// </summary>
        internal static string DateTimeSpan_InvalidTimeSpan {
            get {
                return ResourceManager.GetString("DateTimeSpan_InvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not allowed to be zero..
        /// </summary>
        internal static string DateTimeSpan_TimeSpanZeroNotAllowed {
            get {
                return ResourceManager.GetString("DateTimeSpan_TimeSpanZeroNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start endpoint &apos;{0}&apos; because it has already been started. .
        /// </summary>
        internal static string HostedEndpoint_EndpointAlreadyStarted {
            get {
                return ResourceManager.GetString("HostedEndpoint_EndpointAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve message handler of type &apos;{0}&apos;..
        /// </summary>
        internal static string MessageHandlerClass_CouldNotResolveMessageHandler {
            get {
                return ResourceManager.GetString("MessageHandlerClass_CouldNotResolveMessageHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find implementation of method &apos;{0}.{1}(...)&apos; on type &apos;{3}&apos;..
        /// </summary>
        internal static string MessageHandlerOrQueryInterface_InterfaceMethodNotFound {
            get {
                return ResourceManager.GetString("MessageHandlerOrQueryInterface_InterfaceMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; cannot be used as a component. The type must represent a concrete (non-abstract) type and may not contain unspecified generic parameters..
        /// </summary>
        internal static string MicroProcessorComponent_UnsupportedType {
            get {
                return ResourceManager.GetString("MicroProcessorComponent_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no element at index &apos;{0}&apos; (Count = {1})..
        /// </summary>
        internal static string ReadOnlyList_IndexOutOfRange {
            get {
                return ResourceManager.GetString("ReadOnlyList_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scopes were not nested correctly..
        /// </summary>
        internal static string Scope_IncorrectNesting {
            get {
                return ResourceManager.GetString("Scope_IncorrectNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component of type &apos;{0}&apos; could not be added because it is configured with an invalid lifetime ({1})..
        /// </summary>
        internal static string ServiceCollectionExtensions_InvalidComponentLifetime {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_InvalidComponentLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation to enlist to the current unit of work (as a result of modification of aggregate of type &apos;{0}&apos;), was aborted because execution time exceeded the specified timeout ({1})..
        /// </summary>
        internal static string UnitOfWork_EnlistmentTimeout {
            get {
                return ResourceManager.GetString("UnitOfWork_EnlistmentTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified mode is invalid: {0}..
        /// </summary>
        internal static string UnitOfWork_InvalidMode {
            get {
                return ResourceManager.GetString("UnitOfWork_InvalidMode", resourceCulture);
            }
        }
    }
}
