//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate of type &apos;{0}&apos; cannot publish event of type &apos;{1}&apos; because it has been removed from its repository and its lifetime has therefore ended..
        /// </summary>
        internal static string AggregateRoot_AggregateRemovedException {
            get {
                return ResourceManager.GetString("AggregateRoot_AggregateRemovedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another handler for event of type &apos;{0}&apos; has already been added to this collection..
        /// </summary>
        internal static string AggregateRoot_HandlerForEventTypeAlreadyAdded {
            get {
                return ResourceManager.GetString("AggregateRoot_HandlerForEventTypeAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply event of type &apos;{0}&apos; because it&apos;s Id ({1}) does not match the aggregate&apos;s Id ({2})..
        /// </summary>
        internal static string AggregateRoot_InvalidEventId {
            get {
                return ResourceManager.GetString("AggregateRoot_InvalidEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing event handler for event of type &apos;{0}&apos;..
        /// </summary>
        internal static string AggregateRoot_MissingEventHandlerException {
            get {
                return ResourceManager.GetString("AggregateRoot_MissingEventHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next version ({0}) must represent a newer version than the current version ({1})..
        /// </summary>
        internal static string AggregateRoot_VersionUpdateException {
            get {
                return ResourceManager.GetString("AggregateRoot_VersionUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate of type &apos;{0}&apos; does not support snapshots..
        /// </summary>
        internal static string AggregateRootDecorator_SnapshotsNotSupported {
            get {
                return ResourceManager.GetString("AggregateRootDecorator_SnapshotsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain single attribute of type &apos;{0}&apos; declared on &apos;{1}&apos; because multiple attributes are of type &apos;{0}&apos;..
        /// </summary>
        internal static string AttributeProvider_AmbiguousAttributeMatch {
            get {
                return ResourceManager.GetString("AttributeProvider_AmbiguousAttributeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; must have claim &apos;{1}&apos;..
        /// </summary>
        internal static string ClaimsProvider_ClaimNotFound {
            get {
                return ResourceManager.GetString("ClaimsProvider_ClaimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified object of type &apos;{0}&apos; cannot be compared to instance of type &apos;{1}&apos;..
        /// </summary>
        internal static string Comparable_IncomparableType {
            get {
                return ResourceManager.GetString("Comparable_IncomparableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate object of type &apos;{0}&apos;: constraint &apos;{1}&apos; can only validate instances of type &apos;{2}&apos;..
        /// </summary>
        internal static string Constraint_UnsupportedType {
            get {
                return ResourceManager.GetString("Constraint_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start this scope because a more restrive scope is still active..
        /// </summary>
        internal static string Context_IllegalScopeStarted {
            get {
                return ResourceManager.GetString("Context_IllegalScopeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time span specified: [{0}, {1}]..
        /// </summary>
        internal static string DateTimeSpan_InvalidTimeSpan {
            get {
                return ResourceManager.GetString("DateTimeSpan_InvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not allowed to be zero..
        /// </summary>
        internal static string DateTimeSpan_TimeSpanZeroNotAllowed {
            get {
                return ResourceManager.GetString("DateTimeSpan_TimeSpanZeroNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorLevel must be 0 or higher: {0}..
        /// </summary>
        internal static string ErrorLevel_InvalidErrorLevel {
            get {
                return ResourceManager.GetString("ErrorLevel_InvalidErrorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query could not be executed because of a bad request. See inner exception for details..
        /// </summary>
        internal static string ExecuteAsyncMethod_BadRequest {
            get {
                return ResourceManager.GetString("ExecuteAsyncMethod_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing the query. See inner exception for details..
        /// </summary>
        internal static string ExecuteAsyncMethod_InternalServerError {
            get {
                return ResourceManager.GetString("ExecuteAsyncMethod_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified expression is not supported: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionExtensions_UnsupportedExpression {
            get {
                return ResourceManager.GetString("ExpressionExtensions_UnsupportedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start endpoint &apos;{0}&apos; because it has already been started. .
        /// </summary>
        internal static string HostedEndpoint_EndpointAlreadyStarted {
            get {
                return ResourceManager.GetString("HostedEndpoint_EndpointAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an empty identifier..
        /// </summary>
        internal static string Identifier_EmptyIdentifier {
            get {
                return ResourceManager.GetString("Identifier_EmptyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier specified: &apos;{0}&apos;..
        /// </summary>
        internal static string Identifier_InvalidIdentifier {
            get {
                return ResourceManager.GetString("Identifier_InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing a message. See inner exception for details..
        /// </summary>
        internal static string InternalServerErrorException_FromException {
            get {
                return ResourceManager.GetString("InternalServerErrorException_FromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update aggregate with id &apos;{0}&apos; because its version in the repository ({1}) does not match the expected version ({2}) of the aggregate to be stored. The same aggregate may have been updated by another process..
        /// </summary>
        internal static string MemoryDataStore_ConcurrencyConflict {
            get {
                return ResourceManager.GetString("MemoryDataStore_ConcurrencyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more attributes declared on message &apos;{0}&apos; are assignable to &apos;{1}&apos;..
        /// </summary>
        internal static string Message_AmbiguousAttributeMatch {
            get {
                return ResourceManager.GetString("Message_AmbiguousAttributeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another validator for message of type &apos;{0}&apos; has already been registered..
        /// </summary>
        internal static string Message_ValidatorAlreadyRegisterd {
            get {
                return ResourceManager.GetString("Message_ValidatorAlreadyRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not resolve message handler of type &apos;{1}&apos;..
        /// </summary>
        internal static string MessageHandlerClass_CouldNotResolveMessageHandler {
            get {
                return ResourceManager.GetString("MessageHandlerClass_CouldNotResolveMessageHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InstanceLifetime specified: &apos;{0}&apos;..
        /// </summary>
        internal static string MessageHandlerFactoryBuilder_InvalidInstanceLifetime {
            get {
                return ResourceManager.GetString("MessageHandlerFactoryBuilder_InvalidInstanceLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create instance of type &apos;{0}&apos; because no MessageHandlerFactory has been defined for this processor. Please override method &apos;{1}.{2}&apos; to create and return a custom {3}..
        /// </summary>
        internal static string MessageHandlerFactoryStub_CannotResolveMessageHandler {
            get {
                return ResourceManager.GetString("MessageHandlerFactoryStub_CannotResolveMessageHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message of type &apos;{0}&apos; is not valid: {1}..
        /// </summary>
        internal static string MessageValidationPipeline_InvalidMessage {
            get {
                return ResourceManager.GetString("MessageValidationPipeline_InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate message of type &apos;{0}&apos; because this validator only supports messages of type &apos;{1}&apos;..
        /// </summary>
        internal static string MessageValidator_UnsupportedMessageType {
            get {
                return ResourceManager.GetString("MessageValidator_UnsupportedMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find implementation of method &apos;{0}.{1}({2})&apos; on type &apos;{3}&apos;..
        /// </summary>
        internal static string MethodAttributeProvider_InterfaceMethodNotFound {
            get {
                return ResourceManager.GetString("MethodAttributeProvider_InterfaceMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation of method &apos;{0}()&apos; is not expected at this point..
        /// </summary>
        internal static string MicroProcessorContextState_InvalidOperation {
            get {
                return ResourceManager.GetString("MicroProcessorContextState_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &apos;{0}&apos; specifies an invalid stage: {1}..
        /// </summary>
        internal static string MicroProcessorPipelineFactoryBuilder_InvalidStage {
            get {
                return ResourceManager.GetString("MicroProcessorPipelineFactoryBuilder_InvalidStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache can only be used while a MicroProcessor is handling a message or executing a query..
        /// </summary>
        internal static string NullCache_CacheNotSupported {
            get {
                return ResourceManager.GetString("NullCache_CacheNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; is not supported at this point..
        /// </summary>
        internal static string NullController_OperationNotSupported {
            get {
                return ResourceManager.GetString("NullController_OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot publish event of type &apos;{0}&apos;: events can only be published while a MicroProcessor is handling a message or executing a query..
        /// </summary>
        internal static string NullStream_PublishNotSupported {
            get {
                return ResourceManager.GetString("NullStream_PublishNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified result ({0}) could not be converted to an instance of type &apos;{1}&apos;..
        /// </summary>
        internal static string QueryContext_InvalidResult {
            get {
                return ResourceManager.GetString("QueryContext_InvalidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no element at index &apos;{0}&apos; (Count = {1})..
        /// </summary>
        internal static string ReadOnlyList_IndexOutOfRange {
            get {
                return ResourceManager.GetString("ReadOnlyList_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate of type &apos;{0}&apos; with Id &apos;{1}&apos; was not found..
        /// </summary>
        internal static string Repository_AggregateNotFound {
            get {
                return ResourceManager.GetString("Repository_AggregateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add aggregate of type &apos;{0}&apos; to the repository because another aggregate with Id &apos;{1}&apos; is already present in the data store..
        /// </summary>
        internal static string Repository_DuplicateKeyException_AggregateAlreadyExists {
            get {
                return ResourceManager.GetString("Repository_DuplicateKeyException_AggregateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add mapping for type &apos;{0}&apos; because it has already been mapped..
        /// </summary>
        internal static string SchemaMap_TypeAlreadyMapped {
            get {
                return ResourceManager.GetString("SchemaMap_TypeAlreadyMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add mapping for type-id &apos;{0}&apos; because it has already been mapped..
        /// </summary>
        internal static string SchemaMap_TypeIdAlreadyMapped {
            get {
                return ResourceManager.GetString("SchemaMap_TypeIdAlreadyMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type-id that corresponds to type &apos;{0}&apos; not found..
        /// </summary>
        internal static string SchemaMap_TypeIdNotFound {
            get {
                return ResourceManager.GetString("SchemaMap_TypeIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type that corresponds to type-id &apos;{0}&apos; not found..
        /// </summary>
        internal static string SchemaMap_TypeNotFound {
            get {
                return ResourceManager.GetString("SchemaMap_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete this scope because it is not the current scope..
        /// </summary>
        internal static string Scope_CannotCompleteScope {
            get {
                return ResourceManager.GetString("Scope_CannotCompleteScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scopes were not nested correctly..
        /// </summary>
        internal static string Scope_IncorrectNesting {
            get {
                return ResourceManager.GetString("Scope_IncorrectNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope has already completed..
        /// </summary>
        internal static string Scope_ScopeAlreadyCompleted {
            get {
                return ResourceManager.GetString("Scope_ScopeAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore aggregate of type &apos;{0}&apos; from the retrieved data-set. See inner exception for details..
        /// </summary>
        internal static string SerializationStrategy_CouldNotRestoreAggregate {
            get {
                return ResourceManager.GetString("SerializationStrategy_CouldNotRestoreAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of events per snapshot specified ({0}). Value cannot be negative..
        /// </summary>
        internal static string SerializationStrategy_InvalidEventsPerSnapshot {
            get {
                return ResourceManager.GetString("SerializationStrategy_InvalidEventsPerSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet is missing the expected snapshot..
        /// </summary>
        internal static string SerializationStrategy_MissingSnapshot {
            get {
                return ResourceManager.GetString("SerializationStrategy_MissingSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet is missing the expected snapshot or event to restore the aggregate. .
        /// </summary>
        internal static string SerializationStrategy_MissingSnapshotOrEvent {
            get {
                return ResourceManager.GetString("SerializationStrategy_MissingSnapshotOrEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be used to restore an aggregate..
        /// </summary>
        internal static string SnapshotOrEvent_RestoreNotSupported {
            get {
                return ResourceManager.GetString("SnapshotOrEvent_RestoreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation to enlist to the current unit of work (as a result of modification of aggregate of type &apos;{0}&apos;), was aborted because execution time exceeded the specified timeout ({1})..
        /// </summary>
        internal static string UnitOfWork_EnlistmentTimeout {
            get {
                return ResourceManager.GetString("UnitOfWork_EnlistmentTimeout", resourceCulture);
            }
        }
    }
}
