//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not have expected validation-error &apos;{1}&apos;..
        /// </summary>
        internal static string Request_ErrorMessageNotFound {
            get {
                return ResourceManager.GetString("Request_ErrorMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; was expected to be valid, but {1} validation error(s) occurred..
        /// </summary>
        internal static string Request_InstanceNotValid {
            get {
                return ResourceManager.GetString("Request_InstanceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; was expected to be invalid, but no validation errors occurred..
        /// </summary>
        internal static string Request_InstanceValid {
            get {
                return ResourceManager.GetString("Request_InstanceValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of expected validation errors ({0}) must be equal to or greater than 1..
        /// </summary>
        internal static string Request_InvalidNumberOfExpectedErrorsSpecified {
            get {
                return ResourceManager.GetString("Request_InvalidNumberOfExpectedErrorsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not have any validation-errors..
        /// </summary>
        internal static string Request_MemberErrorsNotFound {
            get {
                return ResourceManager.GetString("Request_MemberErrorsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not contain any validation-error that satisfies the specified predicate..
        /// </summary>
        internal static string Request_NoSuchErrorMessage {
            get {
                return ResourceManager.GetString("Request_NoSuchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of expected validation errors ({0}) does not match the actual amount of validation errors ({1})..
        /// </summary>
        internal static string Request_UnexpectedNumberOfErrorsOccurred {
            get {
                return ResourceManager.GetString("Request_UnexpectedNumberOfErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected error message ({0}) did not match the actual error message ({1})..
        /// </summary>
        internal static string ValidationAttribute_UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("ValidationAttribute_UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value ({0}) was expected to be invalid, but was valid..
        /// </summary>
        internal static string ValidationAttribute_ValidValid {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value ({0}) was expected to be valid, but wasn&apos;t ({1})..
        /// </summary>
        internal static string ValidationAttribute_ValueNotValid {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValueNotValid", resourceCulture);
            }
        }
    }
}
