//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceComponents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceComponents.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event-handler was specified for domain-event of type &apos;{0}&apos;..
        /// </summary>
        internal static string AggregateEventStream_MissingEventHandler {
            get {
                return ResourceManager.GetString("AggregateEventStream_MissingEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key of the event ({0}) must match the key of the aggregate ({1})..
        /// </summary>
        internal static string AggregateRoot_InvalidKey {
            get {
                return ResourceManager.GetString("AggregateRoot_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the event ({0}) must be newer than the version of the aggregate ({1})..
        /// </summary>
        internal static string AggregateRoot_InvalidVersion {
            get {
                return ResourceManager.GetString("AggregateRoot_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute this task because it was already executed or canceled..
        /// </summary>
        internal static string AsyncExecutionTask_TaskAlreadyStarted {
            get {
                return ResourceManager.GetString("AsyncExecutionTask_TaskAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute this method because the current SynchronizationContext is null..
        /// </summary>
        internal static string AsyncObject_ContextNotSet {
            get {
                return ResourceManager.GetString("AsyncObject_ContextNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message of type &apos;{0}&apos; could not be published because it is not valid. See ErrorTree for details..
        /// </summary>
        internal static string BufferedEventBus_InvalidMessage {
            get {
                return ResourceManager.GetString("BufferedEventBus_InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the operation because the cache is currently not available..
        /// </summary>
        internal static string CacheRelay_NotAvailable {
            get {
                return ResourceManager.GetString("CacheRelay_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is already closed..
        /// </summary>
        internal static string Connection_AlreadyClosed {
            get {
                return ResourceManager.GetString("Connection_AlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is already open..
        /// </summary>
        internal static string Connection_AlreadyOpen {
            get {
                return ResourceManager.GetString("Connection_AlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one type found that could be used as an implementation of dependency &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string DependencyClass_AmbigiousMatch {
            get {
                return ResourceManager.GetString("DependencyClass_AmbigiousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; failed..
        /// </summary>
        internal static string DomainModelException_CommandFailed {
            get {
                return ResourceManager.GetString("DomainModelException_CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A handler for event &apos;{0}&apos; has already been registered..
        /// </summary>
        internal static string EventSourcedAggregate_HandlerAlreadyRegistered {
            get {
                return ResourceManager.GetString("EventSourcedAggregate_HandlerAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version cannot be negative: {0}..
        /// </summary>
        internal static string IntXXVersion_NegativeValue {
            get {
                return ResourceManager.GetString("IntXXVersion_NegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is invalid. See ErrorTree for details..
        /// </summary>
        internal static string InvalidMessageException_InvalidMessage {
            get {
                return ResourceManager.GetString("InvalidMessageException_InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more attributes declared on MessageHandler &apos;{0}&apos; are assignable to &apos;{1}&apos;..
        /// </summary>
        internal static string MessageHandler_AmbiguousAttributeMatch {
            get {
                return ResourceManager.GetString("MessageHandler_AmbiguousAttributeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InstanceLifetime was specified on class &apos;{0}&apos;: {1}. .
        /// </summary>
        internal static string MessageHandlerClass_InvalidInstanceLifetimeMode {
            get {
                return ResourceManager.GetString("MessageHandlerClass_InvalidInstanceLifetimeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A module in the query execution pipeline returned an invalid result. Expected result of type &apos;{0}&apos; but was &apos;{1}&apos;..
        /// </summary>
        internal static string MessageOut_InvalidMessageType {
            get {
                return ResourceManager.GetString("MessageOut_InvalidMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enlist &apos;{0}&apos; to the current logical transaction because no such logical transaction is running..
        /// </summary>
        internal static string MessageProcessor_EnlistFailed {
            get {
                return ResourceManager.GetString("MessageProcessor_EnlistFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot publish event &apos;{0}&apos; because no bus is currently available. Make sure all publishing takes place inside a UnitOfWorkScope..
        /// </summary>
        internal static string MessageProcessor_NoEventBusAvailable {
            get {
                return ResourceManager.GetString("MessageProcessor_NoEventBusAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new mapping because the mapping has been switched to read-only state..
        /// </summary>
        internal static string MessageToStrategyMapping_IsReadOnly {
            get {
                return ResourceManager.GetString("MessageToStrategyMapping_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid timeout specified: {0}..
        /// </summary>
        internal static string QueryCacheOptionsAttribute_InvalidTimeoutSpecified {
            get {
                return ResourceManager.GetString("QueryCacheOptionsAttribute_InvalidTimeoutSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query cache kind specified: {0}..
        /// </summary>
        internal static string QueryCacheStrategy_InvalidKindSpecified {
            get {
                return ResourceManager.GetString("QueryCacheStrategy_InvalidKindSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change this collection because it is read-only..
        /// </summary>
        internal static string ReadOnlyDictionary_NotSupported {
            get {
                return ResourceManager.GetString("ReadOnlyDictionary_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aggregate of type &apos;{0}&apos; with the specified key ({1}) was found..
        /// </summary>
        internal static string Repository_AggregateNotFoundByKey {
            get {
                return ResourceManager.GetString("Repository_AggregateNotFoundByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another aggregate with the same key already exists: &apos;{0}&apos;..
        /// </summary>
        internal static string Repository_DuplicateKey {
            get {
                return ResourceManager.GetString("Repository_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete this scope because it is not the current scope..
        /// </summary>
        internal static string TransactionScope_CannotCompleteScope {
            get {
                return ResourceManager.GetString("TransactionScope_CannotCompleteScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope has already completed..
        /// </summary>
        internal static string TransactionScope_ScopeAlreadyCompleted {
            get {
                return ResourceManager.GetString("TransactionScope_ScopeAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope was incorrectly nested or was called from a different thread than it was created on..
        /// </summary>
        internal static string UnitOfWorkScope_IncorrectNestingOrWrongThread {
            get {
                return ResourceManager.GetString("UnitOfWorkScope_IncorrectNestingOrWrongThread", resourceCulture);
            }
        }
    }
}
