//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo.BuildingBlocks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.BuildingBlocks.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) is not valid..
        /// </summary>
        internal static string BasicConstraints_Default {
            get {
                return ResourceManager.GetString("BasicConstraints_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be equal to &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsEqualTo {
            get {
                return ResourceManager.GetString("BasicConstraints_IsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be greater than &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsGreaterThan {
            get {
                return ResourceManager.GetString("BasicConstraints_IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be greater than or equal to &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("BasicConstraints_IsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be within the following range: {constraint.Range}..
        /// </summary>
        internal static string BasicConstraints_IsInRange {
            get {
                return ResourceManager.GetString("BasicConstraints_IsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} of type &apos;{member.Type.FullName}&apos; must be an instance of type &apos;{constraint.Type.FullName}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsInstanceOf {
            get {
                return ResourceManager.GetString("BasicConstraints_IsInstanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not be equal to &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsNotEqualTo {
            get {
                return ResourceManager.GetString("BasicConstraints_IsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not be within the following range: {constraint.Range}..
        /// </summary>
        internal static string BasicConstraints_IsNotInRange {
            get {
                return ResourceManager.GetString("BasicConstraints_IsNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} of type &apos;{member.Type.FullName}&apos; must not be an instance of type &apos;{constraint.Type.FullName}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsNotInstanceOf {
            get {
                return ResourceManager.GetString("BasicConstraints_IsNotInstanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must refer to an instance of an object..
        /// </summary>
        internal static string BasicConstraints_IsNotNull {
            get {
                return ResourceManager.GetString("BasicConstraints_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not refer to the same instance as &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsNotSameInstanceAs {
            get {
                return ResourceManager.GetString("BasicConstraints_IsNotSameInstanceAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be null..
        /// </summary>
        internal static string BasicConstraints_IsNull {
            get {
                return ResourceManager.GetString("BasicConstraints_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must refer to the same instance as &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsSameInstanceAs {
            get {
                return ResourceManager.GetString("BasicConstraints_IsSameInstanceAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be smaller than &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsSmallerThan {
            get {
                return ResourceManager.GetString("BasicConstraints_IsSmallerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be smaller than or equal to &apos;{constraint.Other}&apos;..
        /// </summary>
        internal static string BasicConstraints_IsSmallerThanOrEqualTo {
            get {
                return ResourceManager.GetString("BasicConstraints_IsSmallerThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) did not satisfy the following constraint: &apos;{constraint}&apos;..
        /// </summary>
        internal static string BasicConstraints_MultipleConstraintsFailed {
            get {
                return ResourceManager.GetString("BasicConstraints_MultipleConstraintsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} (true) must be false..
        /// </summary>
        internal static string BooleanConstraints_IsFalse {
            get {
                return ResourceManager.GetString("BooleanConstraints_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} (false) must be true..
        /// </summary>
        internal static string BooleanConstraints_IsTrue {
            get {
                return ResourceManager.GetString("BooleanConstraints_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value.Count} item(s)) contains no element at index {constraint.Index}..
        /// </summary>
        internal static string CollectionConstraints_ElementAt {
            get {
                return ResourceManager.GetString("CollectionConstraints_ElementAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} contains no element at index {constraint.Index}..
        /// </summary>
        internal static string CollectionConstraints_ElementAt_Enumerable {
            get {
                return ResourceManager.GetString("CollectionConstraints_ElementAt_Enumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not be null and contain at least one element..
        /// </summary>
        internal static string CollectionConstraints_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("CollectionConstraints_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value.Count} item(s)) must be null or empty..
        /// </summary>
        internal static string CollectionConstraints_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("CollectionConstraints_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} must be null or empty..
        /// </summary>
        internal static string CollectionConstraints_IsNullOrEmpty_Enumerable {
            get {
                return ResourceManager.GetString("CollectionConstraints_IsNullOrEmpty_Enumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value.Count}) does contain an element index {constraint.Index}..
        /// </summary>
        internal static string CollectionConstraints_NoElementAt {
            get {
                return ResourceManager.GetString("CollectionConstraints_NoElementAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} does contain an element index {constraint.Index}..
        /// </summary>
        internal static string CollectionConstraints_NoElementAt_Enumerable {
            get {
                return ResourceManager.GetString("CollectionConstraints_NoElementAt_Enumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be empty..
        /// </summary>
        internal static string GuidConstraints_IsEmpty {
            get {
                return ResourceManager.GetString("GuidConstraints_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not be empty..
        /// </summary>
        internal static string GuidConstraints_IsNotEmpty {
            get {
                return ResourceManager.GetString("GuidConstraints_IsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value.Count} item(s)) contains no element at index {constraint.Index}..
        /// </summary>
        internal static string ListConstraints_ElementAt {
            get {
                return ResourceManager.GetString("ListConstraints_ElementAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must have a value..
        /// </summary>
        internal static string NullableConstraints_IsNotNull {
            get {
                return ResourceManager.GetString("NullableConstraints_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must contain &apos;{constraint.Value}&apos;..
        /// </summary>
        internal static string StringConstraints_Contains {
            get {
                return ResourceManager.GetString("StringConstraints_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not contain &apos;{constraint.Value}&apos;..
        /// </summary>
        internal static string StringConstraints_DoesNotContain {
            get {
                return ResourceManager.GetString("StringConstraints_DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not end with &apos;{constraint.Postfix}&apos;..
        /// </summary>
        internal static string StringConstraints_DoesNotEndWith {
            get {
                return ResourceManager.GetString("StringConstraints_DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not match pattern &apos;{constraint.Pattern}&apos;..
        /// </summary>
        internal static string StringConstraints_DoesNotMatch {
            get {
                return ResourceManager.GetString("StringConstraints_DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must not start with &apos;{constraint.Prefix}&apos;..
        /// </summary>
        internal static string StringConstraints_DoesNotStartWith {
            get {
                return ResourceManager.GetString("StringConstraints_DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must end with &apos;{constraint.Postfix}&apos;..
        /// </summary>
        internal static string StringConstraints_EndsWith {
            get {
                return ResourceManager.GetString("StringConstraints_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name}&apos;s Length ({member.Value}) must be within range {constraint.Range}..
        /// </summary>
        internal static string StringConstraints_HasLengthBetween {
            get {
                return ResourceManager.GetString("StringConstraints_HasLengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must have a length of {constraint.Length} character(s)..
        /// </summary>
        internal static string StringConstraints_HasLengthOf {
            get {
                return ResourceManager.GetString("StringConstraints_HasLengthOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a byte..
        /// </summary>
        internal static string StringConstraints_IsByte {
            get {
                return ResourceManager.GetString("StringConstraints_IsByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a single character..
        /// </summary>
        internal static string StringConstraints_IsChar {
            get {
                return ResourceManager.GetString("StringConstraints_IsChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 96-bit floating point number..
        /// </summary>
        internal static string StringConstraints_IsDecimal {
            get {
                return ResourceManager.GetString("StringConstraints_IsDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 64-bit floating point number..
        /// </summary>
        internal static string StringConstraints_IsDouble {
            get {
                return ResourceManager.GetString("StringConstraints_IsDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 16-bit integer..
        /// </summary>
        internal static string StringConstraints_IsInt16 {
            get {
                return ResourceManager.GetString("StringConstraints_IsInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 32-bit integer..
        /// </summary>
        internal static string StringConstraints_IsInt32 {
            get {
                return ResourceManager.GetString("StringConstraints_IsInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 64-bit integer..
        /// </summary>
        internal static string StringConstraints_IsInt64 {
            get {
                return ResourceManager.GetString("StringConstraints_IsInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a signed byte..
        /// </summary>
        internal static string StringConstraints_IsSByte {
            get {
                return ResourceManager.GetString("StringConstraints_IsSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 32-bit floating point number..
        /// </summary>
        internal static string StringConstraints_IsSingle {
            get {
                return ResourceManager.GetString("StringConstraints_IsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 16-bit unsigned integer..
        /// </summary>
        internal static string StringConstraints_IsUInt16 {
            get {
                return ResourceManager.GetString("StringConstraints_IsUInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 32-bit unsigned integer..
        /// </summary>
        internal static string StringConstraints_IsUInt32 {
            get {
                return ResourceManager.GetString("StringConstraints_IsUInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) could not be converted to a 64-bit unsigned integer..
        /// </summary>
        internal static string StringConstraints_IsUInt64 {
            get {
                return ResourceManager.GetString("StringConstraints_IsUInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must match pattern &apos;{constraint.Pattern}&apos;..
        /// </summary>
        internal static string StringConstraints_Matches {
            get {
                return ResourceManager.GetString("StringConstraints_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) is not allowed to be null or empty..
        /// </summary>
        internal static string StringConstraints_NotNullOrEmpty {
            get {
                return ResourceManager.GetString("StringConstraints_NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) is not allowed to be null or contain only white space..
        /// </summary>
        internal static string StringConstraints_NotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringConstraints_NotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be either null or empty..
        /// </summary>
        internal static string StringConstraints_NullOrEmpty {
            get {
                return ResourceManager.GetString("StringConstraints_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must be either null or contain only white space..
        /// </summary>
        internal static string StringConstraints_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringConstraints_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {member.Name} ({member.Value}) must start with &apos;{constraint.Prefix}&apos;..
        /// </summary>
        internal static string StringConstraints_StartsWith {
            get {
                return ResourceManager.GetString("StringConstraints_StartsWith", resourceCulture);
            }
        }
    }
}
