//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithErrorMessage is not supported by constraint &apos;{0}&apos;..
        /// </summary>
        internal static string Constraint_WithErrorMessageNotSupported {
            get {
                return ResourceManager.GetString("Constraint_WithErrorMessageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithName is not supported by constraint &apos;{0}&apos;..
        /// </summary>
        internal static string Constraint_WithNameNotSupported {
            get {
                return ResourceManager.GetString("Constraint_WithNameNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance &apos;{0}&apos; of type &apos;{1}&apos; is not supported because it is not an Enum type..
        /// </summary>
        internal static string EnumIsInRangeOfValidValues_UnsupportedValue {
            get {
                return ResourceManager.GetString("EnumIsInRangeOfValidValues_UnsupportedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified node or expression is not supported inside a member expression: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionBuilder_ExpressionNotSupported {
            get {
                return ResourceManager.GetString("ExpressionBuilder_ExpressionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; does not contain an indexer with argument types &apos;[{1}]&apos;..
        /// </summary>
        internal static string HasItemFilter_IndexerNotFound {
            get {
                return ResourceManager.GetString("HasItemFilter_IndexerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified values are not valid to index an array: {0}..
        /// </summary>
        internal static string HasItemFilter_InvalidArrayIndexValues {
            get {
                return ResourceManager.GetString("HasItemFilter_InvalidArrayIndexValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified range is not valid: {0}..
        /// </summary>
        internal static string Range_InvalidRange {
            get {
                return ResourceManager.GetString("Range_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format string specified: &apos;{0}&apos;. Missing closing brace of variable at index {1}..
        /// </summary>
        internal static string StringTemplate_MissingClosingBrace {
            get {
                return ResourceManager.GetString("StringTemplate_MissingClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format string specified: &apos;{0}&apos;. Missing identifier at index {1}..
        /// </summary>
        internal static string StringTemplate_MissingIdentifier {
            get {
                return ResourceManager.GetString("StringTemplate_MissingIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format string specified: &apos;{0}&apos;. Unexpected character &apos;{1}&apos; at index {2}..
        /// </summary>
        internal static string StringTemplate_UnexpectedCharacter {
            get {
                return ResourceManager.GetString("StringTemplate_UnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; does not contain public field or property &apos;{1}&apos;..
        /// </summary>
        internal static string StringTemplateVariable_MemberNotFound {
            get {
                return ResourceManager.GetString("StringTemplateVariable_MemberNotFound", resourceCulture);
            }
        }
    }
}
