//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; has no element at index &apos;{1}&apos;..
        /// </summary>
        internal static string CollectionMember_ElementAt_Failed {
            get {
                return ResourceManager.GetString("CollectionMember_ElementAt_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; has no elements..
        /// </summary>
        internal static string CollectionMember_IsNotNullOrEmpty_Failed {
            get {
                return ResourceManager.GetString("CollectionMember_IsNotNullOrEmpty_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not an empty Guid..
        /// </summary>
        internal static string GuidMember_IsEmpty_Failed {
            get {
                return ResourceManager.GetString("GuidMember_IsEmpty_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is an empty Guid..
        /// </summary>
        internal static string GuidMember_IsNotEmpty_Failed {
            get {
                return ResourceManager.GetString("GuidMember_IsNotEmpty_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not have the required length of &apos;{1}&apos;..
        /// </summary>
        internal static string Member_HasLengthOf_Failed {
            get {
                return ResourceManager.GetString("Member_HasLengthOf_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; has no value..
        /// </summary>
        internal static string Member_HasValue_Failed {
            get {
                return ResourceManager.GetString("Member_HasValue_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not equal to &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsEqualTo_Failed {
            get {
                return ResourceManager.GetString("Member_IsEqualTo_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not greater than &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsGreaterThan_Failed {
            get {
                return ResourceManager.GetString("Member_IsGreaterThan_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsGreaterThanOrEqualTo_Failed {
            get {
                return ResourceManager.GetString("Member_IsGreaterThanOrEqualTo_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not an instance of &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsInstanceOf_Failed {
            get {
                return ResourceManager.GetString("Member_IsInstanceOf_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not in range of &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsIsRange_Failed {
            get {
                return ResourceManager.GetString("Member_IsIsRange_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is equal to &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsNotEqualTo_Failed {
            get {
                return ResourceManager.GetString("Member_IsNotEqualTo_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is in range of &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsNotInRange_Failed {
            get {
                return ResourceManager.GetString("Member_IsNotInRange_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is an instance of &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsNotInstanceOf_Failed {
            get {
                return ResourceManager.GetString("Member_IsNotInstanceOf_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is null..
        /// </summary>
        internal static string Member_IsNotNull_Failed {
            get {
                return ResourceManager.GetString("Member_IsNotNull_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is the same instance as &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsNotSameInstanceAs_Failed {
            get {
                return ResourceManager.GetString("Member_IsNotSameInstanceAs_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not null..
        /// </summary>
        internal static string Member_IsNull_Failed {
            get {
                return ResourceManager.GetString("Member_IsNull_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not the same instance as &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsSameInstanceAs_Failed {
            get {
                return ResourceManager.GetString("Member_IsSameInstanceAs_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not smaller than &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsSmallerThan_Failed {
            get {
                return ResourceManager.GetString("Member_IsSmallerThan_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not smaller than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string Member_IsSmallerThanOrEqualTo_Failed {
            get {
                return ResourceManager.GetString("Member_IsSmallerThanOrEqualTo_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not satisfy the specified constraint..
        /// </summary>
        internal static string Member_Satisfies_Failed {
            get {
                return ResourceManager.GetString("Member_Satisfies_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is required but was not specified..
        /// </summary>
        internal static string RequiredMemberAttribute_MissingRequiredValue {
            get {
                return ResourceManager.GetString("RequiredMemberAttribute_MissingRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not contain &apos;{1}&apos;..
        /// </summary>
        internal static string StringMember_Contains_Failed {
            get {
                return ResourceManager.GetString("StringMember_Contains_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; contains &apos;{1}&apos;..
        /// </summary>
        internal static string StringMember_DoesNotContain_Failed {
            get {
                return ResourceManager.GetString("StringMember_DoesNotContain_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; matches pattern &apos;{1}&apos;..
        /// </summary>
        internal static string StringMember_DoesNotMatch_Failed {
            get {
                return ResourceManager.GetString("StringMember_DoesNotMatch_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not end with &apos;{1}&apos;..
        /// </summary>
        internal static string StringMember_EndsWith_Failed {
            get {
                return ResourceManager.GetString("StringMember_EndsWith_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a byte..
        /// </summary>
        internal static string StringMember_IsByte_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsByte_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a single character..
        /// </summary>
        internal static string StringMember_IsChar_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsChar_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a 96-bit decimal number..
        /// </summary>
        internal static string StringMember_IsDecimal_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsDecimal_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a 64-bit floating point number..
        /// </summary>
        internal static string StringMember_IsDouble_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsDouble_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a 16-bit integer..
        /// </summary>
        internal static string StringMember_IsInt16_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsInt16_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a 32-bit integer..
        /// </summary>
        internal static string StringMember_IsInt32_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsInt32_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a 64-bit integer..
        /// </summary>
        internal static string StringMember_IsInt64_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsInt64_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is either null or empty..
        /// </summary>
        internal static string StringMember_IsNotNullOrEmpty_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsNotNullOrEmpty_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is either null or contains only white space..
        /// </summary>
        internal static string StringMember_IsNotNullOrWhiteSpace_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsNotNullOrWhiteSpace_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a signed byte..
        /// </summary>
        internal static string StringMember_IsSByte_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsSByte_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to a 32-bit floating point number..
        /// </summary>
        internal static string StringMember_IsSingle_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsSingle_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to an unsigned 16-bit integer..
        /// </summary>
        internal static string StringMember_IsUInt16_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsUInt16_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to an unsigned 32-bit integer..
        /// </summary>
        internal static string StringMember_IsUInt32_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsUInt32_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; could not be converted to an unsigned 64-bit integer..
        /// </summary>
        internal static string StringMember_IsUInt64_Failed {
            get {
                return ResourceManager.GetString("StringMember_IsUInt64_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not match pattern &apos;{1}&apos;..
        /// </summary>
        internal static string StringMember_Matches_Failed {
            get {
                return ResourceManager.GetString("StringMember_Matches_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not start with &apos;{1}&apos;..
        /// </summary>
        internal static string StringMember_StartsWith_Failed {
            get {
                return ResourceManager.GetString("StringMember_StartsWith_Failed", resourceCulture);
            }
        }
    }
}
