//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exception of type &apos;{0}&apos;, but no exception was thrown..
        /// </summary>
        internal static string Scenario_ExceptionAssertFailed_NoException {
            get {
                return ResourceManager.GetString("Scenario_ExceptionAssertFailed_NoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exception of type &apos;{0}&apos; but exception of type &apos;{1}&apos; was thrown instead. See inner exception for details..
        /// </summary>
        internal static string Scenario_ExceptionAssertFailed_OtherExceptionType {
            get {
                return ResourceManager.GetString("Scenario_ExceptionAssertFailed_OtherExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected inner exception of type &apos;{0}&apos; but exception of type &apos;{1}&apos; did not have an inner exception..
        /// </summary>
        internal static string Scenario_InnerExceptionNotFound {
            get {
                return ResourceManager.GetString("Scenario_InnerExceptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected inner exception op type &apos;{0}&apos; but it was of type &apos;{1}&apos;..
        /// </summary>
        internal static string Scenario_InnerExceptionOfDifferentType {
            get {
                return ResourceManager.GetString("Scenario_InnerExceptionOfDifferentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of expected events cannot be negative: {0}..
        /// </summary>
        internal static string WriteScenario_InvalidEventCount {
            get {
                return ResourceManager.GetString("WriteScenario_InvalidEventCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of expected events ({0}) does not match the actual amount of published events ({1})..
        /// </summary>
        internal static string WriteScenario_UnexpectedEventCount {
            get {
                return ResourceManager.GetString("WriteScenario_UnexpectedEventCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected event of type &apos;{0}&apos; at index &apos;{1}&apos;, but found event of type &apos;{2}&apos;..
        /// </summary>
        internal static string WriteScenario_UnexpectedEventType {
            get {
                return ResourceManager.GetString("WriteScenario_UnexpectedEventType", resourceCulture);
            }
        }
    }
}
