//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YellowFlare.MessageProcessing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FailureMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FailureMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YellowFlare.MessageProcessing.Resources.FailureMessages", typeof(FailureMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command did not result in the expected exception. .
        /// </summary>
        internal static string ExceptionExpected {
            get {
                return ResourceManager.GetString("ExceptionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects were equal. Value was &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionEqual {
            get {
                return ResourceManager.GetString("ExpressionEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression of type &apos;{0}&apos; had no value..
        /// </summary>
        internal static string ExpressionHasNoValue {
            get {
                return ResourceManager.GetString("ExpressionHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression of type &apos;{0}&apos; has a value: &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionHasValue {
            get {
                return ResourceManager.GetString("ExpressionHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance was not null. Value was: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionIsNotNull {
            get {
                return ResourceManager.GetString("ExpressionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances were not the same. Expected &apos;{0}&apos;, but value was: &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionIsNotSameTheInstance {
            get {
                return ResourceManager.GetString("ExpressionIsNotSameTheInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance was null..
        /// </summary>
        internal static string ExpressionIsNull {
            get {
                return ResourceManager.GetString("ExpressionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances were the same. Value was &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionIsTheSameInstance {
            get {
                return ResourceManager.GetString("ExpressionIsTheSameInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances were not equal. Expected &apos;{0}&apos;, but value was &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionNotEqual {
            get {
                return ResourceManager.GetString("ExpressionNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression was not false..
        /// </summary>
        internal static string ExpressionNotFalse {
            get {
                return ResourceManager.GetString("ExpressionNotFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression was not greater than specified value. Expected a value greater than &apos;{0}&apos;, but value was &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionNotGreater {
            get {
                return ResourceManager.GetString("ExpressionNotGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression was not greater than or equal to the specified value. Expected a value greater than or equal to &apos;{0}&apos;, but value was &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionNotGreaterOrEqual {
            get {
                return ResourceManager.GetString("ExpressionNotGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance was not of expected type. Expected an instance of &apos;{0}&apos;, but instance was of (incompatible) type &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionNotOfCompatibleType {
            get {
                return ResourceManager.GetString("ExpressionNotOfCompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression was not smaller than specified value. Expected a value smaller than &apos;{0}&apos;, but value was &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionNotSmaller {
            get {
                return ResourceManager.GetString("ExpressionNotSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression was not smaller than or equal to the specified value. Expected a value smaller than or equal to &apos;{0}&apos;, but value was &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionNotSmallerOrEqual {
            get {
                return ResourceManager.GetString("ExpressionNotSmallerOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression was not true..
        /// </summary>
        internal static string ExpressionNotTrue {
            get {
                return ResourceManager.GetString("ExpressionNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance was of unexpected type. Did not expect an instance of &apos;{0}&apos;, but instance was of (compatible) type &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionOfCompatibleType {
            get {
                return ResourceManager.GetString("ExpressionOfCompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conjunction-statement failed because the conjunction precondition failed..
        /// </summary>
        internal static string NullStatement_PreconditionFailed {
            get {
                return ResourceManager.GetString("NullStatement_PreconditionFailed", resourceCulture);
            }
        }
    }
}
