//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no element at index &apos;{0}&apos; (Count = {1})..
        /// </summary>
        internal static string AsyncMethodOperationStackTrace_IndexOutOfRange {
            get {
                return ResourceManager.GetString("AsyncMethodOperationStackTrace_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; contains illegal character &apos;{1}&apos; encountered at index &apos;{2}&apos;..
        /// </summary>
        internal static string EndpointNameFormat_IllegalCharacter {
            get {
                return ResourceManager.GetString("EndpointNameFormat_IllegalCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; is missing the closing bracket for placeholder started at index &apos;{1}&apos;..
        /// </summary>
        internal static string EndpointNameFormat_MissingClosingBracket {
            get {
                return ResourceManager.GetString("EndpointNameFormat_MissingClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown placeholder specified: &apos;{0}&apos;..
        /// </summary>
        internal static string EndpointNameFormat_UnknownPlaceholderName {
            get {
                return ResourceManager.GetString("EndpointNameFormat_UnknownPlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with content of type &apos;{0}&apos; is not valid because its content has violated some validation-constraints ({1})..
        /// </summary>
        internal static string Message_ContentNotValid {
            get {
                return ResourceManager.GetString("Message_ContentNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with content of type &apos;{0}&apos; could not be converted to a message with content of type &apos;{1}&apos;..
        /// </summary>
        internal static string Message_ConversionFailed {
            get {
                return ResourceManager.GetString("Message_ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with content of type &apos;{0}&apos; is not valid because its MessageKind ({1}) does not match the expected MessageKind ({2})..
        /// </summary>
        internal static string Message_MessageKindMismatch {
            get {
                return ResourceManager.GetString("Message_MessageKindMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with content of type &apos;{0}&apos; is not valid because its MessageKind is {1} and the processor has been configured to block these kinds of messages with direction &apos;{2}&apos;. Please specify the MessageKind of type &apos;{0}&apos; at the processor&apos;s configuration, or change the configuration to allow the processor to process these kinds of messages..
        /// </summary>
        internal static string Message_UndefinedMessagesBlocked {
            get {
                return ResourceManager.GetString("Message_UndefinedMessagesBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified delay ({0}) is not allowed to be negative..
        /// </summary>
        internal static string MessageBus_NegativeDelayNotAllowed {
            get {
                return ResourceManager.GetString("MessageBus_NegativeDelayNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified direction &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string MessageFactory_InvalidMessageDirection {
            get {
                return ResourceManager.GetString("MessageFactory_InvalidMessageDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified kind &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string MessageFactory_InvalidMessageKind {
            get {
                return ResourceManager.GetString("MessageFactory_InvalidMessageKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another mapping for the specified message-type ({0}) already exists..
        /// </summary>
        internal static string MessageFactoryBuilder_MappingForMessageTypeAlreadyExists {
            get {
                return ResourceManager.GetString("MessageFactoryBuilder_MappingForMessageTypeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve message handler of type &apos;{0}&apos;..
        /// </summary>
        internal static string MessageHandlerClass_CouldNotResolveMessageHandler {
            get {
                return ResourceManager.GetString("MessageHandlerClass_CouldNotResolveMessageHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the CorrelationId of a message ({0}) when the Id of the message has not been specified..
        /// </summary>
        internal static string MessageHeader_IdNotSpecified {
            get {
                return ResourceManager.GetString("MessageHeader_IdNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate message-id for message of type &apos;{0}&apos; because multiple factories were configured for this message-type: {1}..
        /// </summary>
        internal static string MessageIdFactory_MultipleFactoriesAddedForSameMessageType {
            get {
                return ResourceManager.GetString("MessageIdFactory_MultipleFactoriesAddedForSameMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageId-property &apos;{0}&apos; has multiple candidates on message of type &apos;{1}&apos;: {2}. Please make sure the type-hierarchy contains only a single public property with this name..
        /// </summary>
        internal static string MessageIdFormatter_PropertyIsAmbiguous {
            get {
                return ResourceManager.GetString("MessageIdFormatter_PropertyIsAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageId-property &apos;{0}&apos; was not found on message of type &apos;{1}&apos;..
        /// </summary>
        internal static string MessageIdFormatter_PropertyNotFound {
            get {
                return ResourceManager.GetString("MessageIdFormatter_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; cannot be used as a MicroProcessor. Please provider a non-abstract, non-generic MicroProcessor-type..
        /// </summary>
        internal static string MicroProcessorBuilder_InvalidProcessorType {
            get {
                return ResourceManager.GetString("MicroProcessorBuilder_InvalidProcessorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add component of type &apos;{0}&apos; to the service collection because it is configured with an unsupported lifetime ({1}) for this type..
        /// </summary>
        internal static string MicroProcessorComponent_InvalidComponentLifetime {
            get {
                return ResourceManager.GetString("MicroProcessorComponent_InvalidComponentLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use instance of type &apos;{0}&apos; as a MicroProcessorComponent. Only non-abstract classes without generic parameters are supported..
        /// </summary>
        internal static string MicroProcessorComponent_TypeNotSupported {
            get {
                return ResourceManager.GetString("MicroProcessorComponent_TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find implementation of method &apos;{0}.{1}(...)&apos; on type &apos;{3}&apos;..
        /// </summary>
        internal static string MicroProcessorComponentInterface_InterfaceMethodNotFound {
            get {
                return ResourceManager.GetString("MicroProcessorComponentInterface_InterfaceMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resolved message-kind ({0}) is not supported for endpoints. Make sure the message-type&apos;s ({1}) message-kind is correctly configured by use of the {2} or through the {3}-options when configuring the processor..
        /// </summary>
        internal static string MicroProcessorEndpoint_UnuspportedMessageKind {
            get {
                return ResourceManager.GetString("MicroProcessorEndpoint_UnuspportedMessageKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unexpected exception occurred. See inner exception for details..
        /// </summary>
        internal static string MicroProcessorOperation_InternalServerError {
            get {
                return ResourceManager.GetString("MicroProcessorOperation_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was cancelled, possibly due to a timeout..
        /// </summary>
        internal static string MicroProcessorOperation_OperationCancelled {
            get {
                return ResourceManager.GetString("MicroProcessorOperation_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certain operation was cancelled unexpectedly..
        /// </summary>
        internal static string MicroProcessorOperation_OperationCancelledUnexpectedly {
            get {
                return ResourceManager.GetString("MicroProcessorOperation_OperationCancelledUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot publish the specified event(s) inside the constructor of a type that is registered as a &apos;{0}&apos;-type, because this causes a circular reference..
        /// </summary>
        internal static string MicroServiceBus_CircularDependencyDetected {
            get {
                return ResourceManager.GetString("MicroServiceBus_CircularDependencyDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect endpoint &apos;{0}&apos; (Name = {1}) to the service-bus because it is not supported by this client..
        /// </summary>
        internal static string MicroServiceBusClient_EndpointNotSupported {
            get {
                return ResourceManager.GetString("MicroServiceBusClient_EndpointNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller of type &apos;{0}&apos; cannot be started because it has already been started..
        /// </summary>
        internal static string MicroServiceBusController_AlreadyStarted {
            get {
                return ResourceManager.GetString("MicroServiceBusController_AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller of type &apos;{0}&apos; cannot publish the specified event(s) because it has not been (fully) started yet..
        /// </summary>
        internal static string MicroServiceBusController_CannotPublishEvents {
            get {
                return ResourceManager.GetString("MicroServiceBusController_CannotPublishEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller of type &apos;{0}&apos; cannot send the specified command(s) because it has not been (fully) started yet..
        /// </summary>
        internal static string MicroServiceBusController_CannotSendCommands {
            get {
                return ResourceManager.GetString("MicroServiceBusController_CannotSendCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item of type &apos;{0}&apos; with id &apos;{1}&apos; was not found..
        /// </summary>
        internal static string Repository_ItemNotFound {
            get {
                return ResourceManager.GetString("Repository_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve queue of type &apos;{0}&apos; because the resolver cannot find the appropriate constructor. Please make sure this type declares exactly one public constructor..
        /// </summary>
        internal static string StoreAndForwardQueueResolver_CannotFindConstructor {
            get {
                return ResourceManager.GetString("StoreAndForwardQueueResolver_CannotFindConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve queue of type &apos;{0}&apos; because a circular dependency was detected in the pipeline..
        /// </summary>
        internal static string StoreAndForwardQueueResolver_CircularDependencyDetected {
            get {
                return ResourceManager.GetString("StoreAndForwardQueueResolver_CircularDependencyDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enlist instance of type &apos;{0}&apos; because the unit of work controller has been disabled..
        /// </summary>
        internal static string UnitOfWork_Disabled {
            get {
                return ResourceManager.GetString("UnitOfWork_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified mode is invalid: {0}..
        /// </summary>
        internal static string UnitOfWork_InvalidMode {
            get {
                return ResourceManager.GetString("UnitOfWork_InvalidMode", resourceCulture);
            }
        }
    }
}
