//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingo.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no element at index &apos;{0}&apos; (Count = {1})..
        /// </summary>
        internal static string AsyncMethodOperationStackTrace_IndexOutOfRange {
            get {
                return ResourceManager.GetString("AsyncMethodOperationStackTrace_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MessageKind ({0}) specified. Endpoints only support commands and events..
        /// </summary>
        internal static string EndpointAttribute_InvalidMessageKindSpecified {
            get {
                return ResourceManager.GetString("EndpointAttribute_InvalidMessageKindSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve message handler of type &apos;{0}&apos;..
        /// </summary>
        internal static string MessageHandlerClass_CouldNotResolveMessageHandler {
            get {
                return ResourceManager.GetString("MessageHandlerClass_CouldNotResolveMessageHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find implementation of method &apos;{0}.{1}(...)&apos; on type &apos;{3}&apos;..
        /// </summary>
        internal static string MessageHandlerOrQueryInterface_InterfaceMethodNotFound {
            get {
                return ResourceManager.GetString("MessageHandlerOrQueryInterface_InterfaceMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; cannot be used as a MicroProcessor. Please provider a non-abstract, non-generic MicroProcessor-type..
        /// </summary>
        internal static string MicroProcessorBuilder_InvalidProcessorType {
            get {
                return ResourceManager.GetString("MicroProcessorBuilder_InvalidProcessorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use instance of type &apos;{0}&apos; as a MicroProcessorComponent. Only non-abstract classes without generic parameters are supported..
        /// </summary>
        internal static string MicroProcessorComponent_TypeNotSupported {
            get {
                return ResourceManager.GetString("MicroProcessorComponent_TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot publish the specified event(s) inside the constructor of a type that is registered as a &apos;{0}&apos;-type, because this causes a circular reference..
        /// </summary>
        internal static string MicroServiceBus_CircularReferenceDetected {
            get {
                return ResourceManager.GetString("MicroServiceBus_CircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component of type &apos;{0}&apos; could not be added because it is configured with an invalid lifetime ({1})..
        /// </summary>
        internal static string ServiceCollectionExtensions_InvalidComponentLifetime {
            get {
                return ResourceManager.GetString("ServiceCollectionExtensions_InvalidComponentLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation to enlist to the current unit of work (as a result of modification of aggregate of type &apos;{0}&apos;), was aborted because execution time exceeded the specified timeout ({1})..
        /// </summary>
        internal static string UnitOfWork_EnlistmentTimeout {
            get {
                return ResourceManager.GetString("UnitOfWork_EnlistmentTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified mode is invalid: {0}..
        /// </summary>
        internal static string UnitOfWork_InvalidMode {
            get {
                return ResourceManager.GetString("UnitOfWork_InvalidMode", resourceCulture);
            }
        }
    }
}
